### ISSUE TITLE
Latency-Test/Latency_Hardware/OSVR_Latency_hardware_firmware/motion_onset_test/motion_onset_test.ino

### ISSUE THREAD

**Issue by fvzaur** [sensics/Latency-Test#4]
In motion_onset_test.ino void getAccelerometerAndGyroHighCounts(..) has to be declared or defined before moving(void). Current version gives compiling error (Arduino 1.6.7)

**Comment by russell-taylor** [comment]
Interesting.  That function is not called, and there are a lot of other function calls in that program that use undeclared forward references.  Looks like maybe they changed the language to be more restrictive between version 1.0.6 (which this was written for) and 1.6.7 (which is giving you trouble).  Seems like it might have been good to make a major version number change.  The code still compiles fine under 1.0.6.

Fixed this ordering in commit 75fa3b2d7a8850a7c3c061d8bd5dd7ea642422bf, but my guess is that you will find other issues due to the other instances.  If so, please re-open a ticket titled "Port .ino files to Arduino 1.6.7" and describe the general issue.  Or go ahead and adjust them and submit a pull request.
